apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 7.13.2
  count: 1
  elasticsearchRef:
    name: "quickstart"
  podTemplate:
    spec:
      containers:
        - name: kibana
  http:
    service:
      spec:
        type: LoadBalancer
        ports:
          - port: 5601
            targetPort: 5601
            protocol: TCP
